# Generated by Django 3.2.13 on 2023-05-01 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appRafael', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trofeus',
            old_name='descrição',
            new_name='descricao',
        ),
    ]
