# Generated by Django 3.2.13 on 2023-05-01 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appRafael', '0002_rename_descrição_trofeus_descricao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jogadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('posicao', models.CharField(max_length=50)),
                ('numero_camisa', models.CharField(max_length=3)),
                ('caracteristicas', models.TextField()),
                ('aprovação', models.BooleanField()),
            ],
        ),
    ]
